# Generated by Django 4.0.2 on 2022-02-28 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TODOapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='create',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
